name = "partykit-home"
compatibility_date = "2023-02-08"

assets = './dist'

workers_dev = false

routes = [
  { pattern = "*.partykit.io/*", zone_name = "partykit.io" },
  { pattern = "partykit.io/*", zone_name = "partykit.io" }
]

[build]
command = "npm run build"
